### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by duaneharkness** [BerkeleyLearnVerify/Scenic#1]
When I attempt to run one of the examples such as

`python -m scenic examples/gta/badlyParkedCar2.sc`

I get a stack trace with the following error message:

ValueError: Object arrays cannot be loaded when allow_pickle=False

The error occurs at this line:
https://github.com/BerkeleyLearnVerify/Scenic/blob/aea0f991f484a17b640d41b45726fad038398750/src/scenic/simulators/gta/interface.py#L102

I have seen this error in other packages and it is related to a recent change in numpy (I have 1.16.4) that assigned a default value to "allow_pickle". To fix the problem I modified the following line:
https://github.com/BerkeleyLearnVerify/Scenic/blob/aea0f991f484a17b640d41b45726fad038398750/src/scenic/simulators/gta/interface.py#L96

Changing it to 
`with numpy.load(path, allow_pickle=True) as data:`

**Comment by dfremont** [comment]
Many thanks for the report, diagnosis, and patch! I have fixed the code as you suggest (22a2e66733fd665b7edca8b969afc2975e1e0d7a), although I may revisit this later to address the underlying security concern.

**Comment by dfremont** [comment]
The remaining part of this issue was resolved by 1777775e225a281f9913b20e9b35ca86ae87d86b.
