### ISSUE TITLE
Examples Error Invalid Syntax

### ISSUE THREAD

**Issue by FrancyFiore** [BerkeleyLearnVerify/Scenic#101]
Hello,

When I attempt to run one of the examples such as

python -m scenic examples/carla/car.scenic   or   python -m scenic examples/driving/pedestrianAcrossRoad.scenic

I get a stack trace with the following error message:

model scenic.domains.driving.model
                   ^
scenic.syntax.translator.PythonParseError: invalid syntax

Any suggestions on how to solve the problem?

**Comment by Eric-Vin** [comment]
Hello!

Could you provide more information as to how you installed and ran the example, such as your OS, build tool, environment, python version, etc...? Then I can try to reproduce this on my machine.

**Comment by FrancyFiore** [comment]
Certainly,

Ubuntu 20.04
Python 3.7
for the simulator I used Carla, downloaded the repo from GitHub, started with the command "./CarlaUE4.sh"

as for scenic, I downloaded the repo then used the examples in that, and installed Scenic with the command "pip install scenic"

**Comment by Eric-Vin** [comment]
I'm having trouble reproducing this in Python 3.7 on my PopOS machine, which should be quite similar to Ubuntu. The command you're running is without the `-s` flag used to invoke simulation, so the problem definitely doesn't involve Carla. It's also a parsing issue, which leads me to believe that there might be something wrong with your install or Scenic version. Are you using a specific version Scenic from PyPi or Github?

**Comment by Eric-Vin** [comment]
Looking back at your comment I think you may have installed Scenic from PyPi with the command pip install scenic. Could you try installing it locally using the command `python -m pip install -e`. More details can be found here: https://scenic-lang.readthedocs.io/en/latest/quickstart.html
