### ISSUE TITLE
Multiple compilations with varying parameters

### ISSUE THREAD

**Issue by abol-karimi** [BerkeleyLearnVerify/Scenic#102]
I have a loop where I create a few scenarios from the same Scenic file but with different parameters:
https://github.com/abol-karimi/ScenarioComplexity/blob/a630417929a5716a2dea3ee34af02c713aae78fd/generator.py#L723

It worked with Carla 0.9.11, but with Carla 0.9.13, I get an error the second time the loop runs: the actions are not compatible with the ego, I get "agent ... tried incompatible action(s) ...", even though the type of ego seems right when I print it. The first iteration of the loop runs without trouble and I can't figure out what's wrong with the second iteration.

**Comment by Eric-Vin** [comment]
I believe this has been fixed, but please open a new issue with the new template if this is still present.
