### ISSUE TITLE
Scenario generation

### ISSUE THREAD

**Issue by arjunsk07** [BerkeleyLearnVerify/Scenic#104]
Hello @dfremont , Is there any document that tells how to use the scenario compiler?
I need to generate some concrete scenarios for the testing with CARLA?
Is it possible to generate some concrete scenic scenarios with this compiler?

**Comment by dfremont** [comment]
Hello @arjunsk07, you can find Scenic's documentation [here](https://scenic-lang.readthedocs.io/en/latest/). The "Getting Started with Scenic" and "Scenic Tutorial" pages show how to use the Scenic command-line tool to compile Scenic programs and generate concrete scenarios. The "Dynamic Scenarios" tutorial ends with an example of how to run the generated scenarios in CARLA (you'll first need to get CARLA set up for Scenic following the instructions [here](https://scenic-lang.readthedocs.io/en/latest/simulators.html#carla)). Feel free to reopen this issue if you have any problems that you can't find solutions for in the documentation.
