### ISSUE TITLE
Question about Packages

### ISSUE THREAD

**Issue by cjychenjiayi** [BerkeleyLearnVerify/Scenic#106]
![image](https://user-images.githubusercontent.com/71555947/212522921-7d2b0f42-eca9-4f28-a0db-c2b07c0d0a55.png)
While I compiling those command, it seems that some of the command can't be recognized by the compiler
I use the PyPi and run scenic test.scenic
Here are the output of my terminal
![image](https://user-images.githubusercontent.com/71555947/212523001-c8339445-ee56-4407-a419-b64671d5814f.png)
Here are my code
![image](https://user-images.githubusercontent.com/71555947/212523009-1def4a69-d2f1-4bb2-b93a-ea4a5f11f877.png)

Could someone please help me to figure it out, thx a kit

**Comment by dfremont** [comment]
As the comments in those code snippets are supposed to indicate, that isn't Scenic code: the point of that section of the documentation is to illustrate how Scenic is more flexible and readable than if you used a general programming language like Python that wasn't domain-specific. If you keep reading that page, the very next code block *is* Scenic code that does what you want. Sorry this wasn't clear!
