### ISSUE TITLE
'render' issue while composing scenarios using CARLA

### ISSUE THREAD

**Issue by midhunbenny-inv** [BerkeleyLearnVerify/Scenic#107]
CARLA : 0.9.13
Ubuntu: 18.04.06

While running the scenario using the example provided in the document for composing scenarios I get this following error for CARLA `scenic.core.errors.PythonParseError: invalid syntax `. 
So I wrote a code using the scenario for carla which given below 

```
param map = localPath('../../tests/formats/opendrive/maps/CARLA/Town01.xodr')  
param carla_map = 'Town01'
model scenic.simulators.carla.model

EGO_MODEL = "vehicle.audi.a2"
EGO_SPEED = 10

scenario FollowLane2():
    setup:
        lane = Uniform(*network.lanes)
        behavior LaneBehavior(speed=10):
                do FollowLaneBehavior(speed) 
        start = OrientedPoint on lane.centerline
        ego = Car at start,
            with blueprint EGO_MODEL,
            with behavior LaneBehavior(EGO_SPEED)


scenario Main():
    compose:
        do FollowLane2()
```
but upon executing the following code I get the error in the terminal `AttributeError: 'NoneType' object has no attribute 'render'`

Is there anything wrong with the way I wrote the code or is this problem of scenic connecting with the simulator.

**Comment by Eric-Vin** [comment]
Apologies for the late response! I'm having trouble reproducing this error, but if this is still a problem could you open another issue using our new issue template? I think specifically I'll need the complete backtrace to see what's going wrong.
