### ISSUE TITLE
CARLA simulator collision with the road

### ISSUE THREAD

**Issue by jvzacchi** [BerkeleyLearnVerify/Scenic#110]
While using scenic with CARLA simulator, a recurring issue happens while spawning objects. This is a well known problem with CARLA, i.e., when spawing directly on the floor (z=0) the simulator will take a collision with the floor and return an exception. Normally, to avoid that, an offset should e added to the z coordinate in each actor spawn.

**Comment by dfremont** [comment]
Hello @jvzacchi, are you still seeing this issue? If you could send us a file to reproduce it that would be helpful; otherwise I'll close the issue soon (we can always reopen it if you have time later).
