### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by gulnaz-zh** [BerkeleyLearnVerify/Scenic#112]
FAILED tests/test_scenic.py::test_driving_dynamic - AttributeError: module 'signal' has no attribute 'SIGALRM'

I have read that woindows does not have sigalrm, how to solve this issue?

**Comment by Haoxi2002** [comment]
I really also want to know the answer. I have meet the problem last week, then I have tried use WSL2, but it doesn't support CARLA well (because of double GPUs, it can't use NVIDIA GPU). I prepare to use docker, good luck!

**Comment by dfremont** [comment]
Hello folks, thank you for reporting this bug. I believe PR #114 fixes it: could you please give that a try and let me know how it goes? If the fix works for you I will merge it into `main`.

**Comment by Haoxi2002** [comment]
> Hello folks, thank you for reporting this bug. I believe PR #114 fixes it: could you please give that a try and let me know how it goes? If the fix works for you I will merge it into `main`.

Thx! I have already tried under Scenario+CARLA, it works! Thank you very much!
PS: This is my first time participating in Issues and I didn't expect to receive a response. As a college student from China, I am really excited! Thank you again!

**Comment by dfremont** [comment]
Great! Please do let us know if you encounter any other problems.
