### ISSUE TITLE
Parallel Scene Generation

### ISSUE THREAD

**Issue by axelbr** [BerkeleyLearnVerify/Scenic#120]
Hello!
Is it somehow possible to sample scenes in parallel? 
I am trying to reduce the time it takes to generate multiple scenes up front by parallelizing the sampling process over multiple processes.
Something similar to:
```python
def generate(scenario):
  scene, _ = scenario.generate()
  return scene

...

with Pool(len(scenarios)) as pool:
  scenes = pool.map(generate, scenarios)
```

Trying this will result in an AssertionError which originates from the assertion `not veneer.isActive()`. It seems like scenic relies on a bunch of global variables for the sampling process. Is there a way to encapsulate them and to run the sampling process in parallel?

**Comment by Eric-Vin** [comment]
It is possible to sample multiple scenes in parallel by offloading the compilation, as well as the sampling, to a separate process. Here's some code that would do it:

```
def generate(path):
	scenario = scenic.scenarioFromFile(path=path)
	scene, _ = scenario.generate()
	return scene

with Pool(num_cores) as pool:
	scenes = pool.map(generate, [path for _ in range(num_scenarios)])
```

Note that you'll need to use `multiprocess`, not `multiprocessing`, as `pickle` is currently unable to pickle Scenic `Scene` objects while `dill` is.

These is some repeated work in the compilation/pruning of the scenarios, but hopefully this is negligible in your use case compared to the actual sampling. We are working on a better integration of parallel sampling into Scenic, which would avoid this repeated work.

Hope this helps!

**Comment by axelbr** [comment]
Thanks a lot!
Yes, I had to use multiprocess as well to avoid the pickling problem.

**Comment by axelbr** [comment]
And it is not an issue with the scenario specification. I tried several of your examples with it.

**Comment by Eric-Vin** [comment]
Hmm, could you provide the Python program (using one of our example Scenic programs for simplicity) that causes the problem?

**Comment by axelbr** [comment]
Sorry for the delay.
I am using Scenic version 2.1.0b4.
Here's some sample code that should reproduce the error:

```python
import scenic
from multiprocess.pool import Pool
from scenic.core.scenarios import Scene, Scenario
from scenic.simulators.carla import CarlaSimulator


def sample_scene(scenario: Scenario) -> Scene:
    # scenario = scenic.scenarioFromFile(scenario_path)
    scene, _ = scenario.generate()
    return scene


def sample_sequentially(scenario_path: str, num_scenes=10):
    scenarios = [scenic.scenarioFromFile(scenario_path) for _ in range(num_scenes)]
    return [sample_scene(scenario) for scenario in scenarios]


def sample_parallel(scenario_path: str, num_scenes=10):
    scenarios = [scenic.scenarioFromFile(scenario_path) for _ in range(num_scenes)]
    with Pool(num_scenes) as pool:
        scenes = pool.map(sample_scene, scenarios)
    return scenes


scenes = sample_sequentially(
    scenario_path='traffic_lights.scenic',
    num_scenes=5
)
simulator = CarlaSimulator(carla_map='Town01', map_path='Town01.xodr')

for n in range(10):
    scene: Scene = scenes[n % len(scenes)]
    _ = simulator.simulate(scene, maxSteps=100)

```

Here are the files to reproduce it: [sampling.zip](https://github.com/BerkeleyLearnVerify/Scenic/files/11495352/sampling.zip)

**Comment by dfremont** [comment]
@axelbr This issue is hopefully fixed now on the `main` branch -- please let us know if not.

**Comment by axelbr** [comment]
Wow, this was fast. 
Works now with the example above on my end. Thanks!

**Comment by dfremont** [comment]
Great! Thank you for the report.
