### ISSUE TITLE
Carla example spawns on wrong lane

### ISSUE THREAD

**Issue by axelbr** [BerkeleyLearnVerify/Scenic#157]
The[ carla challenge example](https://github.com/BerkeleyLearnVerify/Scenic/blob/main/examples/carla/Carla_Challenge/carlaChallenge8.scenic) sometimes spawns the adversary in the wrong lane. I am wondering if this is a problem with the constraint or Scenic itself.

**Comment by Eric-Vin** [comment]
I'm having trouble reproducing this. If this is still an issue, could you file another issue with the new template which includes more information for troubleshooting? A random seed that causes this behavior would also be helpful.
