### ISSUE TITLE
Cannot run two scenarios back to back

### ISSUE THREAD

**Issue by abol-karimi** [BerkeleyLearnVerify/Scenic#168]
Using Scenic's Python API, I cannot run a scenario immediately after another. For the second simulation, I get the following error:
```Traceback (most recent call last):
  File "tests/scenic2/loop.py", line 28, in <module>
    res2 = simulate()
  File "tests/scenic2/loop.py", line 19, in simulate
    sim_result = simulator.simulate(
  File "/home/carla/Scenic/src/scenic/core/simulators.py", line 76, in simulate
    simulation.run(maxSteps)
  File "/home/carla/Scenic/src/scenic/core/simulators.py", line 216, in run
    raise InvalidScenarioError(f'agent {agent} tried incompatible '
scenic.core.errors.InvalidScenarioError: agent unnamed Car (139820564322960) tried incompatible  action(s) (<scenic.domains.driving.actions.RegulatedControlAction object at 0x7f2a8315ad60>,)
```

Platform:

- Carla 0.9.14 docker
- Python 3.8.17 compiled from source
- Scenic 2.1.0b4

Here is the `loopy.py` script:

```
#!/usr/bin/env python3.8
import scenic

seconds = 20
timestep = .05
render = False

def simulate(scenic_file):
    scenario = scenic.scenarioFromFile(
                    scenic_file,
                    params={'timestep': timestep,
                            'render': render,
                            },
                    cacheImports=False
                    )
    scene, _ = scenario.generate(maxIterations=1)
    simulator = scenario.getSimulator()
    sim_result = simulator.simulate(
                        scene,
                        maxSteps=int(seconds // timestep),
                        maxIterations=1,
                        raiseGuardViolations=True
                        ) 
    return sim_result

res1 = simulate('tests/scenic2/dynamic1.scenic')
res2 = simulate('tests/scenic2/dynamic2.scenic')
```

and the two scenic files `dynamic1.scenic` and `dynamic2.scenic` specify the same scenario:

```
param carla_map = 'Town05'
carla_map = globalParameters.carla_map
param map = f'/home/carla/CarlaUE4/Content/Carla/Maps/OpenDrive/{carla_map}.xodr'
model scenic.simulators.carla.model

p0 = network.intersections[0].incomingLanes[0].centerline.pointAlongBy(0)

ego = Car at p0, facing roadDirection,
  with behavior FollowLaneBehavior(4)
```

**Comment by abol-karimi** [comment]
Thanks for the quick reply! The minimal example above works fine with v2.1. However, my actual scenic code (which is a modular scenario)  still triggers the same error.

**Comment by Eric-Vin** [comment]
Can you provide your example that reproduces it? Then we can investigate why things are still crashing.

**Comment by abol-karimi** [comment]
I see that `scenic.simulators.carla.actions` keeps a reference to `scenic.simulators.carla.model` in order to access the `Vehicle` and `Pedestrian` classes, which seems similar to the bug that was fixed.

**Comment by dfremont** [comment]
You're right, good catch! We'll think about how to fix this.

**Comment by dfremont** [comment]
@abol-karimi Hopefully this is now fixed in `main`; please give it a try and let us know.

**Comment by abol-karimi** [comment]
I applied your changes to v2.1.0 and it works, thank you!

I had tried porting my project to Scenic 3 but I noticed a significant slow down.

**Comment by Eric-Vin** [comment]
Glad to hear it's working now. We'll back-port the fix to 2.x!

How much of a slowdown are you experiencing? We're definitely trying to avoid a significant slowdown for 2.0 scenarios in Scenic 3.0. Could you share your scenario with us so that we can profile it and try to ameliorate the slowdown.

**Comment by abol-karimi** [comment]
That would be great! Since we want to publish the results, the code is in a private repository. I'll add you to the repo and will show you how to run it.

**Comment by Eric-Vin** [comment]
Sounds good! If you'd like you can email me at evin {at} ucsc.edu

**Comment by Eric-Vin** [comment]
The patch (and several others) have been back-ported to 2.x in this PR: https://github.com/BerkeleyLearnVerify/Scenic/pull/173 . 

Please let me know if there's any other issues, but I'll go ahead and close the issue for now.
