### ISSUE TITLE
mp4 file does not get generated

### ISSUE THREAD

**Issue by swatimshah** [BerkeleyLearnVerify/Scenic#198]
Hello there, 

**scenic carlaChallenge1.scenic --simulate --count 1 --param resolution "1920x1080" --param video_output_path "test.mp4" --param timestep 0.0166** 

I am able to run the above command successfully and could run the simulation for 38 seconds. However, the mp4 file does not get regenerated on "pygame window" closure. There is no error logged on the console. Could you please guide me where I am going wrong?

**Comment by Eric-Vin** [comment]
Hello!

I don't believe that parameter currently has any special significance to Scenic or the Carla simulator interface. Are you maybe using a fork of Scenic that added it?

**Comment by swatimshah** [comment]
Hello! Thanks a lot for your response. So far, I am working with the latest scenic code out of below "Scenic" repository.
[https://github.com/BerkeleyLearnVerify/Scenic/tree/main](url). 
However, I am using the below blog article for my work. 
[https://rocketloop.de/en/blog/video-capture-scenic-scenarios-carla/](url)
The "Fork" url in the above link is inaccessible.  (Giving a 404 error).
Could you please refer me to the right fork URL for capturing videos?

**Comment by Eric-Vin** [comment]
Unfortunately that fork isn't something we created, and we don't currently support recording simulation videos in Scenic/Carla. However this is something we're hoping to support in the future.
