### ISSUE TITLE
Spawning vehicle in the intersection

### ISSUE THREAD

**Issue by Nancy22-NJ** [BerkeleyLearnVerify/Scenic#200]
`advInitLane = Uniform(*filter(lambda m: m.type is ManeuverType.STRAIGHT,
        Uniform(*filter(lambda m: m.type is ManeuverType.STRAIGHT, egoInitLane.maneuvers)).conflictingManeuvers)
    ).startLane`

After reading the example scenarios in NHTSA, it seems that we can spawn the vehicle on the lateral entry(right or left randomly) of intersection? 

But if i want to spawn the vehicle on the right entry only, how should i do? 

Looking forward to your reply!

**Comment by Eric-Vin** [comment]
Hello,

Can you clarify what you'd like to do? Are you trying to place a vehicle uniformly on a specific road out of those entering an intersection?

**Comment by Nancy22-NJ** [comment]
> Hello,
> 
> Can you clarify what you'd like to do? Are you trying to place a vehicle uniformly on a specific road out of those entering an intersection?

For example, i want place the vehicle on the left entry of the intersection.

**Comment by Eric-Vin** [comment]
Hello,
It sounds like what you'd like to do can be accomplished by using the `roads` [module](https://scenic-lang.readthedocs.io/en/latest/modules/scenic.domains.driving.roads.html#module-scenic.domains.driving.roads) of the driving domain. Specifically the [`Manuever`](https://scenic-lang.readthedocs.io/en/latest/modules/scenic.domains.driving.roads.html#scenic.domains.driving.roads.Maneuver) class and the [`Lane`](https://scenic-lang.readthedocs.io/en/latest/modules/scenic.domains.driving.roads.html#scenic.domains.driving.roads.Lane) (specifically the  `adjacentLanes` attribute of the appropriate lanes to find the leftmost lane).
Hope this helps!
