### ISSUE TITLE
While running same scenario 2 times getting an error

### ISSUE THREAD

**Issue by sumitradagar** [BerkeleyLearnVerify/Scenic#202]
I am using --count 2 . But the simulation run properly only one time and later I got error
![scerror](https://github.com/BerkeleyLearnVerify/Scenic/assets/37659902/749667cb-02fb-473d-98b8-fda47a6ae5c4)

Please help what is the reason for this error?

**Comment by Eric-Vin** [comment]
Hello,

Could you provide the scenario you are using in this example?

**Comment by Eric-Vin** [comment]
Closing as stale. Please reopen if you're still experiencing this issue.
