### ISSUE TITLE
Pedestrian instead of crossing the road consistently in every scene , keeps going in opposite direction as well for some scenes.

### ISSUE THREAD

**Issue by nidhiyatittas** [BerkeleyLearnVerify/Scenic#209]
In examples while running Carla_Challenge\carlaChallenge3_dynamic.scenic ,pedestrian instead of always crossing the road goes in opposite direction for some scenes.

**Comment by Eric-Vin** [comment]
If this issue is still present, could you file another issue with the new issue template? This will give us the information we need to reproduce the error and troubleshoot. Specifically a random seed that reproduces the error would be helpful.
