### ISSUE TITLE
record parameter does not work with relative path

### ISSUE THREAD

**Issue by delenius** [BerkeleyLearnVerify/Scenic#21]
When using the carla backend, e.g.,

```
$ scenic examples/driving/badlyParkedCarPullingIn.scenic \
    --simulate \
    --model scenic.simulators.carla.model \
    --time 200
    -p record ../output
```

nothing is recorded if I use a relative path like above. This may be a carla bug -- it looks like this path is just passed over to the carla library.

**Comment by Daniel-xsy** [comment]
I got the same problem. After changing the relative path to absolute path, the log files can be generated.
