### ISSUE TITLE
How to set destination for ApolloCar in Lgsvl simulator module

### ISSUE THREAD

**Issue by GrayHHHH** [BerkeleyLearnVerify/Scenic#23]
Hi guys, I am wondering if there is any way to set destination for ApolloCar so that it could automatically route and plan to the goal for every simulaton? I have seen that in lg-api there is set_destination function but I am not sure how it works, maybe could you please give some examples? Thx!

**Comment by dfremont** [comment]
Sorry for the slow reply! Were you able to figure this out? You can use the `DriveTo` behavior to tell Apollo where to drive, e.g. `ApolloCar with behavior DriveTo(destination)`. This requires LG's library for communicating with Dreamview, but that library is now available publicly: in fact the LG folks made a PR for using it, which I'll merge in soon. Then we can add some example scenarios that make use of it.

**Comment by GrayHHHH** [comment]
> Sorry for the slow reply! Were you able to figure this out? You can use the `DriveTo` behavior to tell Apollo where to drive, e.g. `ApolloCar with behavior DriveTo(destination)`. This requires LG's library for communicating with Dreamview, but that library is now available publicly: in fact the LG folks made a PR for using it, which I'll merge in soon. Then we can add some example scenarios that make use of it.

Thanks for your reply! And I am wondering why in the applyTo() in class SetDestinationAction there is a initial throttle setting equals 0.5? And if I change the value to 0.0, the Planning module of Apollo will not work. Is there any synchronization problem? I am asking this question because this initial throttle makes every test's initial position of ApolloCar undetermined. Thanks!

**Comment by dfremont** [comment]
In our experiments with Apollo, it often would not start driving from a complete stop, and you had to press the up arrow briefly to apply some throttle before it would start driving. We emulate that hack in Scenic by applying a throttle of 0.5 for one second. It is really an ugly hack and adds an unwanted delta to the car's initial position as you point out, so it would be great if we could get rid of it. We're planning to do some more testing with Apollo soon and will check if this workaround is no longer necessary.

**Comment by Eric-Vin** [comment]
Closing this as the LGSVL simulator has been deprecated.
