### ISSUE TITLE
how to use `scenic` command  from command line?

### ISSUE THREAD

**Issue by PyTorr** [BerkeleyLearnVerify/Scenic#26]
Hi,

I installed scenic using pip.
How can I run an example? (**scenic** examples/driving/pedestrian.scenic)

Thanks.

**Comment by dfremont** [comment]
@PyTorr Sorry for the slow reply! The command you gave above should work (it's one of the examples in our [documentation](https://scenic-lang.readthedocs.io/en/latest/quickstart.html)); what error message are you getting?

**Comment by PyTorr** [comment]
I uninstalled and installed and in the end it worked. 
I'm not sure what made it work on the end.

**Comment by kannidekan** [comment]
> @PyTorr Sorry for the slow reply! The command you gave above should work (it's one of the examples in our [documentation](https://scenic-lang.readthedocs.io/en/latest/quickstart.html)); what error message are you getting?

Is there something needed to set? (Like command path?) It's just a python package, how to use with `scenic` in the terminal directly?
