### ISSUE TITLE
Cars in NewtonianSimulator do not always get rendered on correct coordinates

### ISSUE THREAD

**Issue by JACY24** [BerkeleyLearnVerify/Scenic#304]
### System Details

1. Pytthon 3.10.8
2. Scenic 3.0.0
3. Microsoft Windows Version 23H2
4. Newtonian simulator (the built in version)

### Detailed Description

1. When running a simulation with the newtonian simulator, the cars seem to not always get rendered on the location that they say they are. In the simulator, there is an if-else statement that draws a car if an object is a car and a polygon otherwise. I tried removing this statement and just drawing both, and the two do not overlap in the rendered simulation, see the screenshots.
2. I ran `scenic examples/driving/badlyParkedCarPullingIn.scenic --2d --simulate --model scenic.simulators.newtonian.driving_model --time 200`
3. ![scenario](https://github.com/user-attachments/assets/7a713090-028b-43e9-8e08-7af10055762e)
![scenario_1](https://github.com/user-attachments/assets/2d805721-447e-43b2-a35a-289163f0ae68)

### Steps To Reproduce

1. Open `Scenic\src\scenic\simulators\newtonian\simulator.py`
2. Go to line 217
3. Replace the if-statement with:
```
            # if hasattr(obj, "isCar") and obj.isCar:
            self.rotated_car = pygame.transform.rotate(
                self.car, math.degrees(obj.heading)
            )
            self.screen.blit(self.rotated_car, (rect_x, rect_y))
            # else:
            corners = [self.scenicToScreenVal(corner) for corner in obj._corners2D]
            pygame.draw.polygon(self.screen, color, corners)
```
The only thing this should do is draw both a Polygon and a car, the logic of the location should not be changed.
4. In the terminal, run ```scenic examples/driving/badlyParkedCarPullingIn.scenic --2d --simulate --model scenic.simulators.newtonian.driving_model --time 200```
6. See the resulting error

### Issue Submission Checklist

- [X] I am reporting an issue, not asking a question
- [X] I checked the open and closed issues, forum, etc. and have not found any solution
- [X] I have provided all necessary code, etc. to reproduce the issue

**Comment by Eric-Vin** [comment]
Apologies for the late response! This definitely looks incorrect: I'll figure out what's wrong and make a patch.
