### ISSUE TITLE
could not generate pedestrian in specific place

### ISSUE THREAD

**Issue by WangRuofeng1998** [BerkeleyLearnVerify/Scenic#306]
### System Details

Python Version --Python 3.10
Scenic Version   --scenic2.1.0
Operating System / Platform ubuntu 22.04
Simulator Version --CARLA 0.9.15

### Detailed Description

1. I could not generate a pedestrian in a specific place, but this place belongs to the sidewalk and I could generate the pedestrian by python. could you please tell me how the do it in scenic?
2. Scenic test.scenic --simulate 
3.scenic.core.distributions.RejectionException: failed to generate scenario in 10000 iterations

## SET MAP AND MODEL (i.e. definitions of all referenceable vehicle types, road library, etc)
param map = localPath('../../../assets/maps/CARLA/Town10HD.xodr')
param carla_map = 'Town10HD'
model scenic.simulators.carla.model

ego = Pedestrian at (-36,118) 

### Issue Submission Checklist

- [X] I am reporting an issue, not asking a question
- [X] I checked the open and closed issues, forum, etc. and have not found any solution
- [ ] I have provided all necessary code, etc. to reproduce the issue

**Comment by Eric-Vin** [comment]
In general with this kind of issue (Scenic being unable to sample a valid scene from a scenario), it's best to use the `-v` flag to specify a higher verbosity. This will show what's causing the rejections, in this case:

```
Rejected sample X because of Containment violation: unnamed Pedestrian is not contained in its container
```

By default a Pedestrian must be in the walkable region of the network. To override this, you can specify `with regionContainedIn everywhere`, which should allow a scene to be sampled.

**Comment by Eric-Vin** [comment]
Going to close this issue for now and move any further discussion to the forum [here](https://forum.scenic-lang.org/t/generate-pedestrian-in-scenic/39/2).
