### ISSUE TITLE
How to apply the scenario generated by Scenic in SVL Simulator and run Apollo 5.0 with it ？How to save these generated scenarios？

### ISSUE THREAD

**Issue by 201520906050** [BerkeleyLearnVerify/Scenic#31]
Recently I used Scenic to generate some dynamic scenarios and ran them with SVL Simulator, but I found that there's no way to use Scenic Command to run the Scenic scripts in SVL Simulator with Apollo, and the scenarios can't be saved to local file system in order to reuse it next time. The scenarios are generated only when the terminal is running，when it‘s closed nothing will be left.

**Comment by Eric-Vin** [comment]
Closing this due to LGSVL interface deprecation.
