### ISSUE TITLE
/.local/lib/python3.8/site-packages/scenic/simulators/carla/behaviors.scenic

### ISSUE THREAD

**Issue by lym-ay** [BerkeleyLearnVerify/Scenic#94]
when I run carlaChallenge4.scenic, the error is "NameError: name '_model' is not defined".But I can't find _model,who tell me where is _model

**Comment by lym-ay** [comment]
FYI

**Comment by Eric-Vin** [comment]
Closing this as I am unable to reproduce the issue. Please file a new issue with the new template if this problem persists.
